version: '3.5'

services:
  db:
    image: postgres:10.4
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:5.0.3-alpine
    ports:
      - '6380:6379'

  api:
    build: .
    volumes:
      - .:/usr/src/app/:cached
      - /usr/src/app/packages/api/node_modules/
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - "db"
      - "redis"
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "npm", "start"] # Wait for postgres
